// demo/src/components/AppSidebar.svelte
<script lang="ts">
  import { link, location } from "svelte-spa-router";
  import { examples } from "../router";

  export let noHeader = false;

  const meta = examples.find((example) => example.path === $location);
</script>

<aside class="basis-1/3 overflow-hidden shadow-xl">
  <div class="h-full flex flex-col bg-inherit overflow-x-hidden overflow-y-auto">
    {#if !noHeader}
      <header class="p-10 pb-5 flex justify-between gap-5 sticky top-0 bg-inherit">
        <a href="/" use:link>Back to Menu</a>
        <a href={meta.sourceUrl} target="_blank">Source</a>
      </header>
    {/if}

    <article class="p-10 flex flex-col gap-3" class:pt-0={!noHeader}>
      <h1 class="break-all">
        <slot name="title" />
      </h1>

      <slot />
    </article>
  </div>
</aside>

<style lang="postcss">
  ::-webkit-scrollbar {
    width: 10px;
    @apply bg-transparent;
  }

  ::-webkit-scrollbar-thumb {
    @apply bg-slate-600 hover:bg-slate-500 rounded-md border-2 border-amber-50;
  }
</style>

// demo/src/components/AppSidebar.vue
<template>
  <aside class="basis-1/3 overflow-hidden shadow-xl">
    <div class="h-full flex flex-col bg-inherit overflow-x-hidden overflow-y-auto">
      <header v-if="!props.noHeader" class="p-10 pb-5 flex justify-between gap-5 sticky top-0 bg-inherit">
        <router-link :to="{ name: 'Menu' }">Back to Menu</router-link>
        <a :href="sourceLink" target="_blank">Source</a>
      </header>

      <article class="p-10 flex flex-col gap-3" :class="{ 'pt-0': !props.noHeader }">
        <h1 class="break-all">
          <slot name="title" />
        </h1>

        <slot name="default" />
      </article>
    </div>
  </aside>
</template>

<script setup lang="ts">
  import { ref } from "vue";
  import { useRoute } from "vue-router";

  const props = defineProps<{
    noHeader?: boolean;
  }>();

  const sourceLink = ref(
    `https://github.com/maplibre/maplibre-gl-directions/tree/main/demo/src/${useRoute().matched[0].meta["originPath"]}`,
  );
</script>

<style scoped>
  ::-webkit-scrollbar {
    width: 10px;
    @apply bg-transparent;
  }

  ::-webkit-scrollbar-thumb {
    @apply bg-slate-600 hover:bg-slate-500 rounded-md border-2 border-amber-50;
  }
</style>
