// demo/src/examples/1 User Interaction.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { examples } from "../router";
  import { location } from "svelte-spa-router";
  import AppSidebar from "../components/AppSidebar.svelte";
  import maplibregl from "maplibre-gl";
  import "maplibre-gl/dist/maplibre-gl.css";
  import style from "../assets/map/style/style.json?url";
  import MapLibreGlDirections from "@maplibre/maplibre-gl-directions";

  const meta = examples.find((example) => example.path === $location);

  let mapRef: HTMLElement | undefined = undefined;
  let directions: MapLibreGlDirections | undefined = undefined;
  let interactive = true;

  onMount(() => {
    const map = new maplibregl.Map({
      container: mapRef,
      style,
      center: [-74.1197632, 40.6974034],
      zoom: 11,
      customAttribution: "<a href='http://project-osrm.org/' target='_blank'>&copy; OSRM</a>",
    });

    map.on("load", () => {
      directions = new MapLibreGlDirections(map, {
        requestOptions: {
          alternatives: "true",
        },
      });
    });
  });

  $: if (directions) {
    directions.interactive = interactive;
  }
</script>

<AppSidebar>
  <span slot="title">{meta.name}</span>

  <label class="flex items-center gap-3">
    <input type="checkbox" bind:checked={interactive} disabled={!directions} />
    <strong>Interactivity enabled</strong>
  </label>

  <ul>
    <li>Click somewhere on the map to add a waypoint</li>
    <li>Click a waypoint to remove it and its related snappoint</li>
    <li>Click a snappoint to remove it and its related waypoint</li>
    <li>Drag a waypoint somewhere to move it</li>
    <li>Drag a routeline somewhere to add a waypoint in-between the 2 nearest ones</li>
    <li>
      Click an alternative routeline to select it<br />
      <small
        ><strong>Note</strong>, there's usually no alternative routelines in the server response if there are more than
        2 waypoints</small
      >
    </li>
  </ul>
</AppSidebar>

<div bind:this={mapRef} class="shadow-xl" />

// demo/src/examples/1 User Interaction.vue
<template>
  <app-sidebar>
    <template #title>{{ name }}</template>

    <label class="flex items-center gap-3">
      <input v-model="interactive" type="checkbox" />
      <strong>Interactivity enabled</strong>
    </label>

    <ul>
      <li>Click somewhere on the map to add a waypoint</li>
      <li>Click a waypoint to remove it and its related snappoint</li>
      <li>Click a snappoint to remove it and its related waypoint</li>
      <li>Drag a waypoint somewhere to move it</li>
      <li>Drag a routeline somewhere to add a waypoint in-between the 2 nearest ones</li>
      <li>
        Click an alternative routeline to select it<br />
        <small
          ><strong>Note</strong>, there's usually no alternative routelines in the server response if there are more
          than 2 waypoints</small
        >
      </li>
    </ul>
  </app-sidebar>

  <div ref="mapRef" class="shadow-xl" />
</template>

<script setup lang="ts">
  import { computed, onMounted, ref } from "vue";
  import { useRoute } from "vue-router";
  import AppSidebar from "../components/AppSidebar.vue";
  import maplibregl from "maplibre-gl";
  import "maplibre-gl/dist/maplibre-gl.css";
  import style from "../assets/map/style/style.json?url";
  import MapLibreGlDirections from "@maplibre/maplibre-gl-directions";

  const name = ref(useRoute().matched[0].name);

  const directions = ref<MapLibreGlDirections>();

  const mapRef = ref();
  onMounted(() => {
    const map = new maplibregl.Map({
      container: mapRef.value,
      style,
      center: [-74.1197632, 40.6974034],
      zoom: 11,
      customAttribution: "<a href='http://project-osrm.org/' target='_blank'>&copy; OSRM</a>",
    });

    map.on("load", () => {
      directions.value = new MapLibreGlDirections(map, {
        requestOptions: {
          alternatives: "true",
        },
      });

      directions.value.interactive = true;
    });
  });

  const interactive = computed({
    get() {
      return directions.value?.interactive ?? false;
    },

    set(value: boolean) {
      if (directions.value) {
        directions.value.interactive = value;
      }
    },
  });
</script>
